<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jxa</string>
		<string>jxainc</string>
		<string>js</string>
	</array>
	<key>name</key>
	<string>JavaScript for Automation (JXA)</string>
	<key>comment</key>
	<string>https://github.com/idleberg/vscode-applescript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.jxa</string>
	<key>uuid</key>
	<string>1d9fb1ad-346c-4b80-9b9f-5daff26885d7</string>
</dict>
</plist>