name: Publish Extension

on:
  push:
    tags:
      - "*"

jobs:
  default:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Lint Source
        run: pnpm exec biome ci

      - name: Run Tests
        run: pnpm run --if-present test

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          dependencies: false
          pat: ${{ secrets.OVSX_PERSONAL_ACCESS_TOKEN }}
          skipDuplicate: true

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          dependencies: false
          pat: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          skipDuplicate: true
